import { readSource } from '../../test/read-source'
import { describe, expect, it } from 'vitest'

describe('repository advanced settings layout', () => {
  it('matches the mockup card stack for tokens, maintenance, and danger actions', () => {
    const source = readSource('src/components/repository-detail/settings-tab.tsx')
    const globals = readSource('src/app/globals.css')

    expect(source).toContain('settings-tab-shell')
    expect(source).toContain('w-full')
    expect(source).not.toContain('max-w-[68.75rem]')
    expect(source).toContain('gap-3.5')
    expect(source).not.toContain('px-[22px]')

    expect(source).toContain('Token created — copy it now')
    expect(source).toContain('border-[#fde68a]')
    expect(source).toContain('bg-gradient-to-b from-[#fffbeb] to-white')
    expect(source).toContain('Copy token')
    expect(source).toContain('Setup for')
    expect(source).toContain('Claude Desktop')
    expect(source).toContain('Cursor')
    expect(source).toContain('Generic JSON')
    expect(source).toContain('Copy config')
    expect(source).toContain('Test connection')

    expect(source).toContain('settings-token-card')
    expect(source).toContain('Issue scoped tokens for Claude Desktop, Cursor, or other MCP clients.')
    expect(source).toContain('All token owners')
    expect(source).toContain('New token')
    expect(source).toContain('showCreateTokenForm')
    expect(source).toContain('settings-token-table')
    expect(source).toContain('border-separate border-spacing-0')
    expect(source).toContain('<colgroup>')
    expect(source).toContain('settings-token-health-cell')
    expect(source).toContain('settings-token-actions')
    expect(source).toContain('token.alertCount > 0 &&')
    expect(source).toContain('token.owner.id !== currentUserId')
    expect(source).toContain('<th>Label</th>')
    expect(source).toContain('<th>Owner</th>')
    expect(source).toContain('<th>Scopes</th>')
    expect(source).toContain('<th>Last used</th>')
    expect(source).toContain('<th>Health</th>')
    expect(source).toContain('<th>Expires</th>')
    expect(globals).toContain('.settings-token-table th')
    expect(globals).toContain('background: var(--convergekit-bg-2)')
    expect(globals).toContain('padding: 9px 20px')
    expect(globals).toContain('white-space: nowrap')
    expect(globals).toContain('.settings-token-actions')
    expect(source).not.toContain("Alerts {token.alertCount > 0 ? `(${token.alertCount})` : ''}")

    expect(source).toContain('grid-cols-1 gap-3.5 md:grid-cols-2')
    expect(source).toContain('Re-index repository')
    expect(source).toContain('Re-clone, parse, and embed everything from scratch.')
    expect(source).toContain('Regenerate Wiki')
    expect(source).toContain('Skip indexing; rebuild pages from current chunks.')

    expect(source).toContain('Danger zone')
    expect(source).toContain('border-[#fecaca]')
    expect(source).toContain('Deleting a repository removes all indexed data, wiki pages, chats, and tokens.')
  })
})
